# Generated by Django 5.2 on 2025-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmedia',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='business_media/cover'),
        ),
        migrations.AlterField(
            model_name='businessmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_media/'),
        ),
        migrations.AlterField(
            model_name='businessmedia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_media/logo'),
        ),
    ]
